# Generated by Django 3.0.6 on 2020-06-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_remove_teacher_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='allowances',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='basic_salary',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='hra',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
