# Generated by Django 3.0.6 on 2020-07-02 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20200701_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Salary'),
        ),
    ]
