# Generated by Django 3.0.6 on 2020-06-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200623_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type_of_user',
            field=models.CharField(choices=[('s', 'student'), ('t', 'teacher'), ('a', 'admin')], default='a', max_length=2),
        ),
    ]
