# Generated by Django 3.0.6 on 2020-06-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_classname_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classname',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='fees',
        ),
        migrations.AddField(
            model_name='fee',
            name='development_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='registration_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='tution_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
