# Generated by Django 3.0.6 on 2020-07-01 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200630_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_deleted',
            new_name='is_user_deleted',
        ),
    ]
