# Generated by Django 3.0.6 on 2020-07-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20200701_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_user_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
