# Generated by Django 3.0.6 on 2020-07-01 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20200701_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_user_deleted',
        ),
    ]
