# Generated by Django 3.0.6 on 2020-07-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_remove_customuser_is_user_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_user_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
