# Generated by Django 3.0.6 on 2020-07-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_customuser_is_user_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='development_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classname',
            name='registration_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classname',
            name='tution_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
