# Generated by Django 3.0.6 on 2020-07-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200701_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'present'), ('A', 'absent'), ('L', 'leave'), ('H', 'Half-day')], default='A', max_length=1)),
                ('reason', models.CharField(choices=[('s', 'Sick Leave')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosumed_leaves', models.PositiveIntegerField()),
                ('allocated_leaves', models.PositiveIntegerField()),
            ],
        ),
    ]
