# Generated by Django 3.0.6 on 2020-06-30 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0004_classname_fee'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.ClassName'),
        ),
        migrations.DeleteModel(
            name='ClassName',
        ),
    ]
