# Generated by Django 3.0.6 on 2020-06-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200630_0827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
