# Generated by Django 3.0.6 on 2020-07-15 08:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20200715_1355'),
        ('student', '0005_auto_20200701_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.date(2020, 7, 15))),
                ('attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Attendance')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.ClassName')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
