# Generated by Django 3.0.6 on 2020-07-16 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 7, 16)),
        ),
    ]
